controller_list:
  - name: fake_arm_controller
    joints:
      - Rev17
      - Rev20
      - Rev26
      - Rev36
      - Rev40
      - Rev45
initial:  # Define initial robot poses.
  - group: arm
    pose: home