# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Rev17
    - Rev20
    - Rev26
    - Rev36
    - Rev40
    - Rev45
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Rev17
      - Rev20
      - Rev26
      - Rev36
      - Rev40
      - Rev45
arm_joint_state_controller:
  type: position_controllers/JointPositionController
  joints:
    - Rev17
    - Rev20
    - Rev26
    - Rev36
    - Rev40
    - Rev45
  gains:
    Rev17:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev20:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev26:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev36:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev40:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev45:
      p: 100
      d: 1
      i: 1
      i_clamp: 1