arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev1
    - Rev2
    - Rev4
    - Rev3
    - Rev5
  gains:
    Rev1: { p: 100, d: 1, i: 1, i_clamp: 1 }
    Rev2: { p: 100, d: 1, i: 1, i_clamp: 1 }
    Rev4: { p: 100, d: 1, i: 1, i_clamp: 1 }
    Rev3: { p: 100, d: 1, i: 1, i_clamp: 1 }
    Rev5: { p: 100, d: 1, i: 1, i_clamp: 1 }
  state_publish_rate: 25

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - G_Rev1
    - G_Rev2
  gains:
    G_Rev1: { p: 100, d: 1, i: 1, i_clamp: 1 }
    G_Rev2: { p: 100, d: 1, i: 1, i_clamp: 1 }
  state_publish_rate: 25
