# GLOBAL OPERATION PARAMETERS
loop_rate: 100                    # desired rate for joint state updates. actual rate may be less depending on number
# of dynamixels on each port
control_mode: position            # control mode, either 'position', 'velocity', or 'effort'
disable_torque_on_shutdown: true  # with this enabled the motors will switch off when the controller closes
ignore_input_velocity: false      # ignore input velocity commands in position mode (no profile velocity)
diagnostics_rate: 1               # rate to publish diagnostic information
dataport_rate: 1                  # rate to read from dynamixel external dataports
# 9.8 5.5 11.2 11.0 6.8 (5.3 3.9) cm
# The below values are used as global defaults and are applied for each servo unless overridden in the entry for the servo below
global_max_vel: 0.3               # maximum joint speed (rad/s) (in position or velocity control)
global_torque_limit: 1          # maximum motor torque for all modes, given as a fraction of rated max (0-1)

# RT AND SERVO CONFIGURATIONS
ports:

    #PORT LIST
    - name: Port_1               # name for this port in config
      device: /dev/ttyUSB0       # serial device this port will communicate on
      baudrate: 1000000            # baudrate in use
      use_legacy_protocol: true # wether to use new 2.0 protocol (false) or legacy 1.0 protocol (true)
      group_read_enabled: false   # specify whether to use group comms for reading
      group_write_enabled: false  # specify whether to use group comms for writing
      servos:
          # SERVO LIST FOR THIS PORT
          - id: 1                # (ID set in servo eeprom, must be unique on this port)
            joint_name: joint_1  # (MUST BE UNIQUE ACROSS ALL PORTS)
            #
            # The three values below are mandatory, they define the orientation and zeroing of the dynamixel:
            #
            zero_pos: 623        # initial (0 rad) servo position (in raw encoder count)
            min_pos: 0           # minimum servo position (in raw encoder count)
            max_pos: 1000        # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
          - id: 2                # (ID set in servo eeprom, must be unique on this port)
            joint_name: joint_2  # (MUST BE UNIQUE ACROSS ALL PORTS)
            zero_pos: 519        # initial (0 rad) servo position (in raw encoder count)
            min_pos: 0         # minimum servo position (in raw encoder count)
            max_pos: 1000        # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED

          - id: 3                # (ID set in servo eeprom, must be unique on this port)
            joint_name: joint_3  # (MUST BE UNIQUE ACROSS ALL PORTS)
            zero_pos: 511        # initial (0 rad) servo position (in raw encoder count)
            min_pos: 0         # minimum servo position (in raw encoder count)
            max_pos: 1000        # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
          - id: 4                # (ID set in servo eeprom, must be unique on this port)
            joint_name: joint_4  # (MUST BE UNIQUE ACROSS ALL PORTS)
            zero_pos: 499        # initial (0 rad) servo position (in raw encoder count)
            min_pos: 0         # minimum servo position (in raw encoder count)
            max_pos: 1000        # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
          - id: 5                # (ID set in servo eeprom, must be unique on this port)
            joint_name: joint_5  # (MUST BE UNIQUE ACROSS ALL PORTS)
            zero_pos: 523        # initial (0 rad) servo position (in raw encoder count)
            min_pos: 0         # minimum servo position (in raw encoder count)
            max_pos: 1000        # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
          - id: 6                # (ID set in servo eeprom, must be unique on this port)
            joint_name: eef  # (MUST BE UNIQUE ACROSS ALL PORTS)
            zero_pos: 315       # initial (0 rad) servo position (in raw encoder count)
            min_pos: 115         # minimum servo position (in raw encoder count)
            max_pos: 315         # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
