# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
   sim_control_mode: 0 # 0: position, 1: velocity

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   # These joints can likely just be copied from the hardware_interface list above
   joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
   constraints:
      goal_time: 5.0
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      Rev1:
          trajectory: 0.60
          goal:       0.15
      Rev2:
          trajectory: 0.60
          goal:       0.15
      Rev3:
          trajectory: 0.60
          goal:       0.15
      Rev4:
          trajectory: 0.60
          goal:       0.15
      Rev5:
          trajectory: 0.60
          goal:       0.15
   # gains:
   #     joint1: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint2: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}

    # state_publish_rate:  50 # Defaults to 50
    # action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

# Group Position Controllers ---------------------------------------
# Allows to send single ROS msg of Float64MultiArray to all joints
joint_position_controller:
   type: position_controllers/JointGroupPositionController
   joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
controller_list:
  - name: arm_controller 
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - G_Rev1
      - G_Rev2
