standalone_tags:
  [

    {id: 0, size: 0.0254},
    {id: 1, size: 0.0254},
    {id: 2, size: 0.0254},
    {id: 3, size: 0.0254},
    {id: 4, size: 0.0254},
    {id: 5, size: 0.0254},
    {id: 6, size: 0.0254},
    {id: 7, size: 0.0254},
    {id: 8, size: 0.0254},
    {id: 9, size: 0.0254},
    {id: 10, size: 0.0254},
    {id: 11, size: 0.0254},
    {id: 12, size: 0.0254},
    {id: 13, size: 0.0254},
    {id: 14, size: 0.0254},
    {id: 15, size: 0.0254},
  ]
