controller_list:
  - name: fake_arm_controller
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
  - name: fake_gripper_controller
    joints:
      - Rev5
      - Rev6
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: open