controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - G_Rev1
      - G_Rev2
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: open