controller_list:
  - name: fake_robot_arm_controller
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
  - name: fake_gripper_controller
    joints:
      - Rev6
      - Rev7
initial:  # Define initial robot poses.
  - group: robot_arm
    pose: home