# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Rev1
    - Rev2
    - Rev3
    - Rev4
    - Rev5
    - Rev6
    - Rev7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Rev6
      - Rev7
robot_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - Rev1
    - Rev2
    - Rev3
    - Rev4
    - Rev5
  gains:
    Rev1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_joint_controller:
  type: position_controllers/JointPositionController
  joints:
    - Rev6
    - Rev7
  gains:
    Rev6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1